services:
  api-facturacion-sri:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-facturacion-sri
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      PORT: 8080
      TEMPLATES_DIR: /data/templates
      PDFS_DIR: /data/pdfs
      CERTS_DIR: /data/certs
      XMLS_DIR: /data/xmls
    volumes:
      - ../data/templates:/data/templates
      - ../data/pdfs:/data/pdfs
      - ../data/certs:/data/certs
      - ../data/xmls:/data/xmls
